app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173,https://ashy-river-03ca7400f.7.azurestaticapps.net}

# DATABASE
spring.datasource.url=jdbc:postgresql://ep-falling-king-aq2gx2d2.c-8.us-east-1.aws.neon.tech/CO2X?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7SycVl0JKZUd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#testeamos deploy linux
# SERVER
# server.port=8080

# AZURE ENTRA
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/cbb64725-bd29-4b87-93b2-e5fcf09ff37f/
spring.security.oauth2.resourceserver.jwt.audiences=api://36920833-e50a-48be-b51a-e363b373c011
azure.client.id=36920833-e50a-48be-b51a-e363b373c011

azure.scope=api://36920833-e50a-48be-b51a-e363b373c011/.default

# IPFS
pinata.api.key=ef9654cefac901ff9951
pinata.api.secret=23f67277c07a9070223f746c47d6f715498f8e7b524cf79ac49963f305edf88b
