spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/co2x
    username: postgres
    password: postgre
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/co2x
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  server:
    port: 8080

