spring.config.import=optional:file:.env[.properties],optional:file:proyectoIntegradorBack/.env[.properties]

app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173,https://ashy-river-03ca7400f.7.azurestaticapps.net}

# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

server.error.include-message=always
server.error.include-stacktrace=never

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#testeamos deploy linux
# SERVER
# server.port=8080

# AZURE ENTRA
spring.security.oauth2.resourceserver.jwt.issuer-uri=${ENTRA_ISSUER_URI:https://sts.windows.net/cbb64725-bd29-4b87-93b2-e5fcf09ff37f/}
spring.security.oauth2.resourceserver.jwt.audiences=${ENTRA_AUDIENCE:api://36920833-e50a-48be-b51a-e363b373c011}
azure.client.id=${ENTRA_CLIENT_ID:36920833-e50a-48be-b51a-e363b373c011}

azure.scope=${ENTRA_SCOPE:api://36920833-e50a-48be-b51a-e363b373c011/.default}

# IPFS
pinata.api.key=${PINATA_API_KEY}
pinata.api.secret=${PINATA_API_SECRET}

# BLOCKCHAIN

blockchain.rpc.url=${BLOCKCHAIN_RPC_URL:https://rpc-amoy.polygon.technology/}

blockchain.private.key=${BLOCKCHAIN_PRIVATE_KEY}

blockchain.contract.address=${BLOCKCHAIN_CONTRACT_ADDRESS:0x58a072F97f213513cfa798Af4483AAe8D93fd24c}

blockchain.destination.wallet=${BLOCKCHAIN_DESTINATION_WALLET:0xd85DefFdf312092a1e6DbF19919914De53D8D9e1}
