# DATABASE
spring.datasource.url=jdbc:postgresql://ep-falling-king-aq2gx2d2.c-8.us-east-1.aws.neon.tech/CO2X?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7SycVl0JKZUd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
# server.port=8080

# AZURE ENTRA
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/cbb64725-bd29-4b87-93b2-e5fcf09ff37f/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://36920833-e50a-48be-b51a-e363b373c011
azure.client.id=36920833-e50a-48be-b51a-e363b373c011
azure.client.secret=qOy8Q~JyrZXYfXqts84LhopQjafacs3FF6Uinb.S
azure.scope=api://36920833-e50a-48be-b51a-e363b373c011/.default