
# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy

name: Build and deploy JAR app to Azure Web App - CO2XLinux

on:
  push:
    branches:
      - main
    paths:
      - 'proyectoIntegradorBack/**'
      - '.github/workflows/develop_co2xlinux.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./proyectoIntegradorBack

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/proyectoIntegradorBack/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      - name: Debug IDs
        run: echo "Using configured Azure credentials"
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: "36920833-e50a-48be-b51a-e363b373c011"
          tenant-id: "cbb64725-bd29-4b87-93b2-e5fcf09ff37f"
          subscription-id: "c38be5e0-c994-47b0-8631-84c325f9f5d9"
          allow-no-subscriptions: true
      - name: Azure Account List
        run: az account list --output table
      - name: Azure Account Show
        run: az account show
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CO2XLinux'
          slot-name: 'Production'
          package: '*.jar'

