name: Deploy CO2XBackend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend with Maven
        run: mvn clean install -DskipTests
        working-directory: ./proyectoIntegradorBack

      - name: Publish artifact
        run: mvn package -DskipTests
        working-directory: ./proyectoIntegradorBack

      - name: Deploy to Azure WebApp (Windows)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CO2XBackend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_CREDENTIALS }}
          package: ./proyectoIntegradorBack/target/*.jar
